---
- name: install epel yum repository
  yum:
    name: epel-release

- name: install webtatic yum repository
  yum:
    name: https://mirror.webtatic.com/yum/el6/latest.rpm

- name: install php
  yum:
    name: "{{ item }}"
    enablerepo: epel
  with_items:
    - php-php-gettext
    - php-tcpdf
    - php-tcpdf-dejavu-sans-fonts
    - php70w
    - php70w-bcmath
    - php70w-cli
    - php70w-common
    - php70w-gd
    - php70w-intl
    - php70w-mbstring
    - php70w-mcrypt
    - php70w-mysql
    - php70w-opcache
    - php70w-pecl-apcu
    - php70w-pecl-redis
    - php70w-pecl-xdebug
    - php70w-pdo
    - php70w-process
    - php70w-tidy
    - php70w-xml

- name: set config file for Apache
  template:
    src: php.conf.j2
    dest: /etc/httpd/conf.d/php.conf
    owner: root
    group: root
    mode: 0644

- name: download installation shell for composer
  uri:
    url: https://raw.githubusercontent.com/composer/getcomposer.org/1b137f8bf6db3e79a38a5bc45324414a6b1f9df2/web/installer
    dest: /tmp/install_composer.php
    creates: /tmp/install_composer.php

- name: install composer
  command: php /tmp/install_composer.php --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: set symlink for composer
  file:
    path: /usr/bin/composer
    state: link
    src: /usr/local/bin/composer
    owner: root
    group: root
